export const FULL_ACCESS_ROLE_NAMES = ["Owner", "Super Admin"];
export const SYSTEM_ROLE_NAMES = [
  "Owner",
  "Admin Manager",
  "Finance Manager",
  "Content Manager",
  "Content Writer",
  "Listings Moderator",
  "Support Agent",
  "Marketing Manager",
  "Analytics Viewer",
];

export const PERMISSION_ROUTE_ACCESS = {
  "/admin/dashboard": [
    "viewAnalytics",
    "viewListings",
    "viewDealers",
    "viewBlogs",
    "viewPromotions",
    "viewNotifications",
    "viewAuctions",
    "manageUsers",
    "manageSupportTickets",
    "viewInquiries",
    "viewFinancialReports",
    "viewAuditLogs",
  ],
  "/admin/users": ["manageUsers", "viewUserProfiles"],
  "/admin/listings": [
    "viewListings",
    "approveListings",
    "editListings",
    "createListings",
    "deleteListings",
    "featureListings",
  ],
  "/admin/dealers": [
    "viewDealers",
    "approveDealers",
    "editDealers",
    "createDealers",
    "deleteDealers",
  ],
  "/admin/categories": [
    "viewCategories",
    "createCategories",
    "editCategories",
    "deleteCategories",
    "manageCategories",
  ],
  "/admin/blogs": [
    "viewBlogs",
    "createBlogs",
    "editBlogs",
    "deleteBlogs",
    "manageBlogs",
    "publishBlogs",
    "moderateComments",
  ],
  "/admin/blogs/categories": ["viewCategories", "manageCategories", "editCategories"],
  "/admin/blogs/create": ["createBlogs", "manageBlogs"],
  "/admin/blog-comments": ["moderateComments"],
  "/admin/blogs/media": ["manageBlogs", "createBlogs"],
  "/admin/testimonials": ["viewTestimonials", "manageTestimonials", "moderateComments"],
  "/admin/analytics": ["viewAnalytics", "viewFinancialReports", "createReports", "exportReports"],
  "/admin/activity-log": ["viewAuditLogs"],
  "/admin/chat-monitoring": [
    "accessChatbot",
    "viewChatbotLogs",
    "createChatLogs",
    "editChatLogs",
    "deleteChatLogs",
  ],
  "/admin/support-chat": [
    "manageSupportTickets",
    "respondToInquiries",
    "createSupportTickets",
    "deleteSupportTickets",
  ],
  "/admin/customer-requests": [
    "viewInquiries",
    "createInquiries",
    "respondToInquiries",
    "editInquiries",
    "deleteInquiries",
  ],
  "/admin/valuations": ["viewAnalytics", "viewListings"],
  "/admin/account-deletion-requests": [
    "manageUsers",
    "viewUserProfiles",
    "viewFullUserProfiles",
    "accessSensitiveAreas",
  ],
  "/admin/promotions": [
    "viewPromotions",
    "createPromotions",
    "editPromotions",
    "deletePromotions",
    "managePromotions",
  ],
  "/admin/payments": ["viewFinancialReports", "managePayments", "manageCommission"],
  "/admin/notifications": [
    "viewNotifications",
    "createNotifications",
    "editNotifications",
    "deleteNotifications",
    "sendPushNotifications",
    "createPushNotifications",
  ],
  "/admin/auctions": ["viewAuctions", "manageAuctions"],
  "/admin/settings": [
    "viewSettings",
    "managePlatformSettings",
    "editSettings",
    "manageLogo",
    "manageLanguage",
    "manageCurrency",
    "manageCommission",
  ],
  "/admin/banners": ["manageBanners", "managePlatformSettings"],
};

export const LEGACY_PATH_ALIASES = {
  "/admin/blog-categories": "/admin/blogs/categories",
  "/admin/blog-media": "/admin/blogs/media",
  "/admin/chat": "/admin/chat-monitoring",
  "/admin/chatbot": "/admin/chat-monitoring",
  "/admin/support-chatbot": "/admin/support-chat",
  "/admin/contact-form": "/admin/customer-requests",
};

export const PERMISSION_KEYS = [
  "manageUsers",
  "createRoles",
  "editRoles",
  "deleteRoles",
  "inviteUsers",
  "resetPasswords",
  "viewListings",
  "createListings",
  "approveListings",
  "editListings",
  "deleteListings",
  "featureListings",
  "viewDealers",
  "createDealers",
  "approveDealers",
  "editDealers",
  "deleteDealers",
  "manageDealerSubscriptions",
  "viewDealerPerformance",
  "viewCategories",
  "createCategories",
  "editCategories",
  "deleteCategories",
  "manageCategories",
  "manageCarTypes",
  "viewBlogs",
  "createBlogs",
  "editBlogs",
  "deleteBlogs",
  "manageBlogs",
  "publishBlogs",
  "moderateComments",
  "viewTestimonials",
  "manageTestimonials",
  "viewPromotions",
  "createPromotions",
  "editPromotions",
  "deletePromotions",
  "managePromotions",
  "viewNotifications",
  "createNotifications",
  "editNotifications",
  "deleteNotifications",
  "createPushNotifications",
  "sendPushNotifications",
  "accessChatbot",
  "viewChatbotLogs",
  "createChatLogs",
  "editChatLogs",
  "deleteChatLogs",
  "manageSupportTickets",
  "createSupportTickets",
  "deleteSupportTickets",
  "respondToInquiries",
  "escalateIssues",
  "viewInquiries",
  "createInquiries",
  "editInquiries",
  "deleteInquiries",
  "viewAnalytics",
  "viewFinancialReports",
  "createReports",
  "exportReports",
  "editReports",
  "deleteReports",
  "viewAuctions",
  "manageAuctions",
  "viewSettings",
  "createSettings",
  "editSettings",
  "deleteSettings",
  "managePlatformSettings",
  "manageLogo",
  "manageLanguage",
  "manageCurrency",
  "manageCommission",
  "manageIntegrations",
  "manageBanners",
  "viewAuditLogs",
  "viewUserProfiles",
  "viewFullUserProfiles",
  "accessSensitiveAreas",
  "managePayments",
];

export const ROLE_FORM_MODULES = [
  {
    id: "dashboard",
    label: "Dashboard",
    keys: {
      view: [
        "viewAnalytics",
        "viewListings",
        "viewDealers",
        "viewBlogs",
        "viewPromotions",
        "viewNotifications",
        "viewAuctions",
        "manageUsers",
        "manageSupportTickets",
        "viewInquiries",
        "viewFinancialReports",
        "viewAuditLogs",
      ],
    },
  },
  {
    id: "users",
    label: "User Management",
    keys: {
      view: ["viewUserProfiles", "manageUsers"],
      create: ["inviteUsers"],
      edit: ["manageUsers", "resetPasswords"],
      delete: ["manageUsers"],
      approve: ["createRoles", "editRoles", "deleteRoles"],
    },
  },
  {
    id: "listings",
    label: "Listings",
    keys: {
      view: ["viewListings"],
      create: ["createListings"],
      edit: ["editListings"],
      delete: ["deleteListings"],
      approve: ["approveListings", "featureListings"],
    },
  },
  {
    id: "dealers",
    label: "Dealer Management",
    keys: {
      view: ["viewDealers"],
      create: ["createDealers"],
      edit: ["editDealers"],
      delete: ["deleteDealers"],
      approve: ["approveDealers", "manageDealerSubscriptions"],
    },
  },
  {
    id: "categories",
    label: "Categories",
    keys: {
      view: ["viewCategories"],
      create: ["createCategories", "manageCategories"],
      edit: ["editCategories", "manageCategories"],
      delete: ["deleteCategories", "manageCategories"],
      approve: ["manageCarTypes"],
    },
  },
  {
    id: "blogs",
    label: "Blog Management",
    keys: {
      view: ["viewBlogs"],
      create: ["createBlogs"],
      edit: ["editBlogs"],
      delete: ["deleteBlogs"],
      approve: ["publishBlogs", "moderateComments"],
    },
  },
  {
    id: "testimonials",
    label: "Reviews & Testimonials",
    keys: {
      view: ["viewTestimonials"],
      edit: ["manageTestimonials", "moderateComments"],
      approve: ["manageTestimonials", "moderateComments"],
    },
  },
  {
    id: "analytics",
    label: "Reports & Analytics",
    keys: {
      view: ["viewAnalytics", "viewFinancialReports"],
      create: ["createReports"],
      edit: ["editReports"],
      delete: ["deleteReports"],
      approve: ["exportReports"],
    },
  },
  {
    id: "activity-log",
    label: "Activity Log",
    keys: {
      view: ["viewAuditLogs"],
    },
  },
  {
    id: "chat-monitoring",
    label: "Chat Monitoring",
    keys: {
      view: ["accessChatbot", "viewChatbotLogs"],
      create: ["createChatLogs"],
      edit: ["editChatLogs"],
      delete: ["deleteChatLogs"],
    },
  },
  {
    id: "support-chat",
    label: "Support Chat",
    keys: {
      view: ["manageSupportTickets", "respondToInquiries"],
      create: ["createSupportTickets"],
      edit: ["manageSupportTickets", "respondToInquiries"],
      delete: ["deleteSupportTickets"],
      approve: ["escalateIssues"],
    },
  },
  {
    id: "customer-requests",
    label: "Customer Requests",
    keys: {
      view: ["viewInquiries"],
      create: ["createInquiries"],
      edit: ["editInquiries", "respondToInquiries"],
      delete: ["deleteInquiries"],
    },
  },
  {
    id: "valuations",
    label: "Car Estimator",
    keys: {
      view: ["viewAnalytics", "viewListings"],
      approve: ["exportReports"],
    },
  },
  {
    id: "account-deletion",
    label: "Account Deletion",
    keys: {
      view: ["viewUserProfiles", "viewFullUserProfiles"],
      approve: ["manageUsers", "accessSensitiveAreas"],
    },
  },
  {
    id: "promotions",
    label: "Promotions",
    keys: {
      view: ["viewPromotions"],
      create: ["createPromotions"],
      edit: ["editPromotions"],
      delete: ["deletePromotions"],
      approve: ["managePromotions"],
    },
  },
  {
    id: "payments",
    label: "Payments",
    keys: {
      view: ["viewFinancialReports"],
      edit: ["managePayments", "manageCommission"],
      approve: ["accessSensitiveAreas"],
    },
  },
  {
    id: "notifications",
    label: "Notifications",
    keys: {
      view: ["viewNotifications"],
      create: ["createNotifications"],
      edit: ["editNotifications"],
      delete: ["deleteNotifications"],
      approve: ["sendPushNotifications", "createPushNotifications"],
    },
  },
  {
    id: "auctions",
    label: "Auction Management",
    keys: {
      view: ["viewAuctions"],
      create: ["manageAuctions"],
      edit: ["manageAuctions"],
      approve: ["manageAuctions"],
    },
  },
  {
    id: "settings",
    label: "Settings",
    keys: {
      view: ["viewSettings"],
      create: ["createSettings"],
      edit: [
        "editSettings",
        "managePlatformSettings",
        "manageLogo",
        "manageLanguage",
        "manageCurrency",
      ],
      delete: ["deleteSettings"],
      approve: ["manageCommission", "manageIntegrations", "accessSensitiveAreas"],
    },
  },
  {
    id: "banners",
    label: "Banners",
    keys: {
      view: ["manageBanners", "managePlatformSettings"],
      create: ["manageBanners"],
      edit: ["manageBanners"],
      delete: ["manageBanners"],
    },
  },
];
